#!/usr/bin/env bash
# Delete configuration file

usage() {
  cat <<EOF
Usage: me-conf-delete <conf_dir> <conf>

Arguments:
  conf_dir    Configuration directory
  conf        Configuration file
EOF
}

delete_conf() {
  local sure
  if ! me conf-dir-list | grep -E "^$1$" &>/dev/null; then
    echo "Configuration directory '$1' doesn't exist."
    exit 1
  fi

  if ! me list-conf "$1" | grep -E "^$2$" &>/dev/null; then
    echo "Configuration file '$2' doesn't exist."
    exit 1
  fi

  for ((;;)); do
    read -p "Do you really want to delete configuration file '/etc/me-$1.d/$2.conf'? [y/n]: " sure
    if [[ $sure =~ [Yy] ]]; then
      rm -f "/etc/me-$1.d/$2.conf"
      echo "Done."
      break
    elif [[ $sure =~ [Nn] ]]; then
      echo "Ignore."
      break
    fi
  done
}

case $1 in
  '' ) usage ;;
  *  ) delete_conf "$1" "$2" ;;
esac

