#!/usr/bin/env bash
# Edit configuration file

usage() {
  cat <<EOF
Usage: me-list-conf <conf_dir> <conf>

Arguments:
  conf_dir    Configuration directory
  conf        Configuration file
EOF
}

update_conf() {
  local sure
  local conf_temp=$(mktemp)
  local editor=${EDITOR:-nano}

  if ! me list-conf-dir | grep -E "^$1$" &>/dev/null; then
    echo "Configuration directory '$1' doesn't exist."
    exit 1
  fi
  if ! me list-conf "$1" | grep -E "^$2$" &>/dev/null; then
    echo "Configuration file '$2' doesn't exist."
    exit 1
  fi

  cp -f "/etc/me-$1.d/$2.conf" "$conf_temp"
  "$editor" "$conf_temp"

  for ((;;)); do
    read -p "Do you want to save your modification? [y/n]: " sure
    if [[ $sure =~ [Yy] ]]; then
      mv "$conf_temp" "/etc/me-$1.d/$2.conf"
      chmod 644 "/etc/me-$1.d/$2.conf"
      echo "Succeed to create file '/etc/me-$1.d/$2.conf'."
      break
    elif [[ $sure =~ [Nn] ]]; then
      echo "Ignore your modification."
      break
    fi
  done
}

# Main
case $1 in
  ''   ) usage ;;
  *    ) update_conf "$1" "$2" ;;
esac
