#!/usr/bin/env bash
# Log and monitor iptables

LOG=/var/log/iptables.log

usage() {
  cat <<EOF
Usage: me-iptables [<options>]

Options:
  -l, --log      Log iptables
  -v, --view-log View log file of iptables
  -m, --monitor  Monitor iptables
EOF
}

log () {
  me info $(date)
  iptables -vnL --line-numbers
  echo -e "\n\n"
}

monitor() {
  # $1: Chain of iptables
  watch -n 1 iptables --line-numbers -vnL $1
}

# main
case $1 in
  -l|--log      ) log 2>&1 | tee -a $LOG ;;
  -v|--view-log ) less -R $LOG ;;
  -m|--monitor  ) monitor $2 ;;
  *             ) usage ;;
esac

