#!/usr/bin/env bash

usage() {
  cat <<EOF
Usage: me-view-conf <conf_dir> <conf>

Arguments:
  conf_dir    Configuration directory
  conf        Configuration file
EOF
}

view_conf() {
  if ! me list-conf-dir | grep -E "^$1$" &>/dev/null; then
    echo "Configuration directory '$1' doesn't exist."
    exit 1
  fi

  if ! me list-conf "$1" | grep -E "^$2$" &>/dev/null; then
    echo "Configuration file '$2' doesn't exist."
    exit 1
  fi

  cat "/etc/me-$1.d/$2.conf"
}

case $1 in
  '' ) usage ;;
  *  ) view_conf "$1" "$2" ;;
esac
