#!/usr/bin/bash -e

die() {
  echo "${@:2}"
  exit $1
}

system=$(awk -F= '$1=="ID" {print $2}' /etc/os-release | tr -d '"')
case "$system" in
  centos ) yum check-update ;;
  fedora ) dnf check-update ;;
  arch   ) pacman && pacman -Qu ;;
  *      ) die 1 "Unsupport system '$system'" ;;
esac
