#!/usr/bin/bash -e

die() {
  echo "${@:2}"
  exit $1
}

usage() {
  echo "Usage: check_update [-h|--help] [-H|--html]"
  echo ""
  echo "Arguments"
  echo "  -h, --help     Display this help page"
  echo "  -H, --html     Display the result in html"
  exit 0
}

while (( ${#@} > 0 )) ; do
  case $1 in
    -h|--help ) usage ;;
    -H|--html ) html=true ;;
    *         ) die 1 "Unknown argument '$1'" ;;
  esac
  shift
done

if [[ $html == true ]]; then
  prefix="<pre>"
  suffix="</pre>"
else
  prefix=
  suffix=
fi

system=$(awk -F= '$1=="ID" {print $2}' /etc/os-release | tr -d '"')

case "$system" in
  centos ) echo "$prefix$(yum check-update)$suffix" ;;
  fedora ) echo "$prefix$(dnf check-update)$suffix" ;;
  arch   ) echo "$prefix$(pacman -Sy; pacman -Qu)$suffix" ;;
  *      ) die 1 "${prefix}Unsupport system '$system'${suffix}" ;;
esac
