#!/usr/bin/bash

die() {
  echo "${@:2}"
  exit $1
}

usage() {
  echo "Usage: check_iptables [-h|--help] [-H|--html] [-Z|--zero] <TABLE> [<TABLE> ...]"
  echo ""
  echo "Arguments"
  echo "  -h, --help     Display this help page"
  echo "  -H, --html     Display the result in html"
  echo "  -Z, --zero     Zero the packet and byte counters after check"
  echo "  <TABLE>        filter (default), nat, mangle or raw"
  exit 0
}

tables=()
while (( ${#@} > 0 )) ; do
  case $1 in
    -h|--help ) usage ;;
    -H|--html ) html=true ;;
    -Z|--zero ) zero=true ;;
    *         ) if [[ $1 =~ ^filter$|^nat$|^mangle$|^raw$ ]]; then tables+=($1); else die 1 "Unsupport table '$table'"; fi ;;
  esac
  shift
done

if (( ${#tables} == 0 )); then
  usage
fi

if [[ $html == true ]]; then
  prefix="<pre>"
  suffix="</pre>"
else
  prefix=
  suffix=
fi

cmd() {
  for table in "${tables[@]}"; do
    echo "$table:"
    iptables -t "$table" -vnL
    echo -e "\n"
    if [[ $zero == true ]]; then
      iptables -t "$table" -Z
    fi
  done
}
echo "$prefix$(cmd)$suffix"
