#!/usr/bin/bash

die() {
  echo "${@:2}"
  exit $1
}

usage() {
  echo "Usage: $(basename $0) [-h|--help] [-H|--html] [-n|--new] [-x|--proxy <PROXY>] -f|--file <FILE> <SETNAME>"
  echo ""
  echo "Arguments"
  echo "  -h, --help     Display this help page"
  echo "  -H, --html     Display the result in html"
  echo "  -n, --new      Update by downloading new list"
  echo "  -x, --proxy    Use proxy when downloading new list"
  echo "  -f, --file     Use an existed list file. When used with '-n' option, it will save download to this file"
  echo "  <SETNAME>      Setname used by ipset"
  exit 0
}

while (( ${#@} > 0 )) ; do
  case $1 in
    -h|--help  ) usage ;;
    -n|--new   ) new=true ;;
    -H|--html  ) html=true ;;
    -f|--file  ) shift; file=$1 ;;
    -x|--proxy ) shift; proxy="-x $1" ;;
    *          ) if [[ ! -v setname ]]; then setname=$1; else die 1 "Support only one <SETNAME>."; fi ;;
  esac
  shift
done
if [[ ! -v setname ]]; then
  die 1 "No <SETNAME> provided."
fi
if [[ ! -v file ]]; then
  die 1 "No <FILE> provided."
fi

if [[ $html == true ]]; then
  echo "<pre>"
fi

ipset create "$setname" hash:net &> /dev/null ||
  echo "Create '$setname', but it already exists."
ipset create "$setname-swap" hash:net &> /dev/null ||
  die 1 "Create '$setname-swap', but it already exists."

if [[ $new == true ]]; then
  dir=$(dirname "$file")
  if [[ ! -d $dir ]]; then
    ipset destroy "$setname-swap"
    die 1 "Cannot find '$dir'."
  fi
  temp=$(mktemp /tmp/ipset-cn.XXXXX)

  curl $proxy -S -k -o "$temp" \
    'https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt'
else
  if [[ ! -r $file ]]; then
    ipset destroy "$setname-swap"
    die 1 "Cannot read '$file'."
  fi

fi

while read block; do
  ipset add "$setname-swap" "$block" || {
    ipset destroy "$setname-swap"
    exit 1
  }
done < "${temp:-$file}"

ipset list "$setname-swap" | perl -F: -lane '
BEGIN {
  my $es = 0;
}
if (@F[0] =~ /Number of entries/ && @F[1] > 0) {
  $es = 123;
}
END {
  exit $es;
}
'
if (( $? == 123 )); then
  ipset swap "$setname-swap" "$setname" && {
    echo "Swap '$setname-swap' and '$setname'."
    if [[ $new == true ]]; then
      mv "$temp" "$file"
    fi
  }
  ipset destroy "$setname-swap" &&
    echo "Destroy '$setname-swap'."
else
  die 1 "'$setname-swap' is empty."
fi

if [[ $html == true ]]; then
  echo "</pre>"
fi
